language: php

sudo: required

php:
    - 7

compiler:
    - gcc

before_script:
    - git submodule update --init
script:
    - phpize
    - ./configure
    - make all
    - NO_INTERACTION=1 make test
