language: php

sudo: required

php:
    - 5.6
    - 5.5
    - 5.4

compiler:
    - gcc

before_script:
    - git submodule update --init
script:
    - phpize
    - ./configure
    - make all
    - NO_INTERACTION=1 make test
