thirdparty/build/lib/libuv.a:
	@echo "Build libuv"
	cp -pr thirdparty/libuv /tmp && \ 
	cd tmp/libuv && \
	./autogen.sh && \
	CFLAGS="$(CFLAGS) -fPIC"  ./configure --prefix="$(srcdir)/thirdparty/build" && \
	make install
