thirdparty/build/lib/libr3.a:
	@echo "Build r3"
	cd thirdparty/r3 && \
	./autogen.sh && \
	CFLAGS="$(CFLAGS) -fPIC"  ./configure --prefix="$(srcdir)/thirdparty/build" && \
	make install

thirdparty/build/lib/libuv.a:
	@echo "Build libuv"
	cd thirdparty/libuv && \
	./autogen.sh && \
	CFLAGS="$(CFLAGS) -fPIC"  ./configure --prefix="$(srcdir)/thirdparty/build" && \
	make install
